// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductService.Persistence;

#nullable disable

namespace ProductService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251103134554_AddProduct")]
    partial class AddProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductService.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7b8b57c-5d7b-4e8a-9a9c-b2b7d2b21d9f"),
                            Description = "High-fidelity sound with noise cancellation.",
                            ImageUrl = "https://placehold.co/300x200/FFD700/000000?text=Headphones",
                            Name = "Wireless Headphones",
                            Price = 99.99m,
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("c2a9133d-3e52-4c90-bb9d-bbc7b5284b44"),
                            Description = "Track your fitness and receive notifications.",
                            ImageUrl = "https://placehold.co/300x200/87CEEB/000000?text=Smartwatch",
                            Name = "Smartwatch",
                            Price = 199.99m,
                            Stock = 5
                        },
                        new
                        {
                            Id = new Guid("0e3e8e64-df62-4b2e-b34a-7f60b54b07c3"),
                            Description = "Compact and powerful sound on the go.",
                            ImageUrl = "https://placehold.co/300x200/98FB98/000000?text=Speaker",
                            Name = "Portable Bluetooth Speaker",
                            Price = 49.99m,
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("e8a7b9c2-84b1-4a12-9350-fb2caa1b1cdd"),
                            Description = "Comfortable and supportive for long working hours.",
                            ImageUrl = "https://placehold.co/300x200/DDA0DD/000000?text=Chair",
                            Name = "Ergonomic Office Chair",
                            Price = 249.99m,
                            Stock = 3
                        },
                        new
                        {
                            Id = new Guid("f43a1a52-6b42-4dc3-9c2b-2d238fb707f5"),
                            Description = "Stunning visuals for work and entertainment.",
                            ImageUrl = "https://placehold.co/300x200/F08080/000000?text=Monitor",
                            Name = "4K UHD Monitor",
                            Price = 399.99m,
                            Stock = 8
                        },
                        new
                        {
                            Id = new Guid("b58d67f1-d95f-469d-9b18-bac2b8b6d8f2"),
                            Description = "Mechanical keyboard with RGB lighting.",
                            ImageUrl = "https://placehold.co/300x200/ADD8E6/000000?text=Keyboard",
                            Name = "Gaming Keyboard",
                            Price = 79.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = new Guid("b8f21e22-2e39-4bb0-9a49-bb1a99303b9f"),
                            Description = "High-precision sensor for competitive gaming.",
                            ImageUrl = "https://placehold.co/300x200/FFB6C1/000000?text=Mouse",
                            Name = "Gaming Mouse",
                            Price = 39.99m,
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("1a4d8b0a-2b7c-44a3-96b4-c11f0a1d7a77"),
                            Description = "Full HD video calls and streaming.",
                            ImageUrl = "https://placehold.co/300x200/DAA520/000000?text=Webcam",
                            Name = "Webcam 1080p",
                            Price = 59.99m,
                            Stock = 7
                        },
                        new
                        {
                            Id = new Guid("3c51a78b-7f42-4e2c-9f1a-bd7b56e79f51"),
                            Description = "Fast and portable storage solution.",
                            ImageUrl = "https://placehold.co/300x200/B0C4DE/000000?text=SSD",
                            Name = "External SSD 1TB",
                            Price = 129.99m,
                            Stock = 4
                        },
                        new
                        {
                            Id = new Guid("a60a9a16-5f74-4d92-8c2d-7f6d44ef9b60"),
                            Description = "Expand your laptop's connectivity with multiple ports.",
                            ImageUrl = "https://placehold.co/300x200/F4A460/000000?text=USB-C+Hub",
                            Name = "USB-C Hub",
                            Price = 29.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("cf86c4f3-96f3-4f1e-982a-47b3a5f71f5b"),
                            Description = "Compact earbuds with active noise cancellation.",
                            ImageUrl = "https://placehold.co/300x200/C0C0C0/000000?text=Earbuds",
                            Name = "Noise-Cancelling Earbuds",
                            Price = 129.99m,
                            Stock = 9
                        },
                        new
                        {
                            Id = new Guid("0c3f4d82-13b7-4e49-a45b-25db07a3c631"),
                            Description = "Control all your smart devices from one place.",
                            ImageUrl = "https://placehold.co/300x200/D8BFD8/000000?text=Smart+Hub",
                            Name = "Smart Home Hub",
                            Price = 89.99m,
                            Stock = 6
                        },
                        new
                        {
                            Id = new Guid("b0a4a3cc-4c0a-4b73-97cb-cb9a344a1d10"),
                            Description = "Automated cleaning for a spotless home.",
                            ImageUrl = "https://placehold.co/300x200/AFEEEE/000000?text=Vacuum",
                            Name = "Robot Vacuum Cleaner",
                            Price = 299.99m,
                            Stock = 2
                        },
                        new
                        {
                            Id = new Guid("ee14b35d-2a3a-46e3-a47b-f3a1d35117a9"),
                            Description = "Capture stunning photos and videos.",
                            ImageUrl = "https://placehold.co/300x200/F5DEB3/000000?text=Camera",
                            Name = "Digital Camera",
                            Price = 499.99m,
                            Stock = 3
                        },
                        new
                        {
                            Id = new Guid("ac71c501-b889-4742-b41e-61cfc9c3b91a"),
                            Description = "Enjoy movies anywhere with a compact projector.",
                            ImageUrl = "https://placehold.co/300x200/9ACD32/000000?text=Projector",
                            Name = "Portable Projector",
                            Price = 179.99m,
                            Stock = 5
                        },
                        new
                        {
                            Id = new Guid("a3bc612e-1ebd-4d12-95db-748147a4b6e4"),
                            Description = "Monitor your activity, heart rate, and sleep.",
                            ImageUrl = "https://placehold.co/300x200/FFA07A/000000?text=Fitness+Tracker",
                            Name = "Fitness Tracker",
                            Price = 69.99m,
                            Stock = 18
                        },
                        new
                        {
                            Id = new Guid("47a13d15-9e37-4e3d-8c59-48289ac62d6c"),
                            Description = "Advanced cleaning for healthier gums.",
                            ImageUrl = "https://placehold.co/300x200/BDB76B/000000?text=Toothbrush",
                            Name = "Electric Toothbrush",
                            Price = 45.99m,
                            Stock = 14
                        },
                        new
                        {
                            Id = new Guid("8e5130b7-0932-4fa4-97b9-4b68d7c5b07f"),
                            Description = "Cook healthier meals with less oil.",
                            ImageUrl = "https://placehold.co/300x200/E0FFFF/000000?text=Air+Fryer",
                            Name = "Air Fryer",
                            Price = 89.99m,
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("22e7b923-ff07-4c92-bc85-8cc3b4ad72b1"),
                            Description = "Brew your perfect cup of coffee every morning.",
                            ImageUrl = "https://placehold.co/300x200/D2B48C/000000?text=Coffee+Maker",
                            Name = "Coffee Maker",
                            Price = 75.99m,
                            Stock = 8
                        },
                        new
                        {
                            Id = new Guid("0b73a09f-b47f-4ac0-80a9-d91ed9f24c85"),
                            Description = "Control your lighting with your voice or app.",
                            ImageUrl = "https://placehold.co/300x200/F0F8FF/000000?text=Smart+Bulbs",
                            Name = "Smart Light Bulbs (2-pack)",
                            Price = 25.99m,
                            Stock = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
